---
- name: Setup PC for Game Dev
  hosts: local

  tasks:
    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present
      become: true
      become_method: sudo

    - name: Edit .vimrc
      ansible.builtin.blockinfile:
        path: ~/.vimrc
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        block: |
          set number
          syntax on
          set cursorline
          set cursorcolumn
          set shiftwidth=4
          set tabstop=4
          set expandtab
        create: yes

    - name: Download Godot
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/godot-engine.mirror/files/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip/download
        dest: .
