- name: Download Godot
  ansible.builtin.get_url:
   url: https://sourceforge.net/projects/godot-engine.mirror/files/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip/download
   dest: . 

- name: Uncompress Godot
  ansible.builtin.shell:
   cmd: "unzip Godot*.zip -d ~"

- name: Remove archived Godot package
  ansible.builtin.shell:
   cmd: "rm Godot*.zip"

- name: Add godot alias
  ansible.builtin.lineinfile:
   path: ~/.bashrc
   line: alias godot='/home/kevinf/Godot_v4.5.1-stable_linux.x86_64'
