- name: Download Blender
  ansible.builtin.get_url:
   url: https://download.blender.org/release/Blender5.0/blender-5.0.0-linux-x64.tar.xz
   dest: . 

- name: Uncompress Blender
  ansible.builtin.shell:
   cmd: "tar -xvf blender* --directory=/home/kevinf"

- name: Remove archived Blender package
  ansible.builtin.shell:
   cmd: "rm blender*"

- name: Add blender alias
  ansible.builtin.lineinfile:
    line: alias blender='/home/kevinf/blender-5.0.0-linux-x64/blender'
    path: ~/.bashrc

