- name: Download obsidian
  ansible.builtin.get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.6/Obsidian-1.10.6.AppImage
    dest: /home/kevinf/

- name: Make obsidian executable
  ansible.builtin.shell:
    cmd: 'chmod +x ~/Obsidian*'

- name: Add obsidian alias
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: alias obsidian='/home/kevinf/Obsidian-1.10.6.AppImage'
